# python
{
  trainingSetPath : /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/data_set/test_fredag_mlp/test_fredag_mlp_training,
  minNumArticlesPerDewey : !!python/int 60,
  evaluatorConfigPath : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/config/evaluator.yml,
  epochs: !!python/int 1,
  learningRate : !!python/float 0.3,
  lrUpdate : !!python/int 98,
  lossFunction : !!python/str hs,
  wikiVec : !!python/bool False,
  wikiPath : !!python/str lol/lolz ,
  wordWindow : !!python/int 5,
  kLabels : !!python/int 3,
  modelsDirectory : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/testing/fasttext
}