# python
{
  trainingSetPath : /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/data_set/tgcForOptimization/tgcForOptimization_training,
  minNumArticlesPerDewey : !!python/int 50,
  strictArticleSelection: !!python/bool True,
  evaluatorConfigPath : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/config/evaluator.yml,
  epochs: !!python/int 20,
  learningRate : !!python/float 0.3,
  lrUpdate : !!python/int 98,
  lossFunction : !!python/str hs,
  wikiVec : !!python/bool False,
  wikiPath : !!python/str lol/lolz ,
  wordWindow : !!python/int 5,
  kPreds : !!python/int 3,
  modelsDir : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/testing/fasttext
}