# python
{
trainingSetPath : /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/data_set/test_fredag_mlp/test_fredag_mlp_training,
kLabels : !!python/int 3,
minNumArticlesPerDewey : !!python/int 60,
evaluatorConfigPath : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/config/evaluator.yml
}