# python
{
training_set : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/data_set/test_fredag_mlp/test_fredag_mlp_training,
test_set : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/data_set/test_fredag_mlp/test_fredag_mlp_test,
vectorizationType: !!python/str count,
minNumArticlesPerDewey : !!python/int 150,
kPreds : !!python/int 5,
modelsDirectory : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/testing/logReg,
evaluatorConfigPath : !!python/str /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/config/evaluator.yml
}