 # python
{
    trainingSetPath : !!python/str /home/knutf/Dokumenter/test_fredag_mlp/test_fredag_mlp_training,
    testSetPath : !!python/str  /home/knutf/Dokumenter/test_fredag_mlp/test_fredag_mlp_test,
    vocabSizeVector : [2000],
    configFolder : !!python/str /home/knutf/workspace/shipping_ready/tgpl_oop/config/config_MLP_run,
    logFolder : !!python/str /home/knutf/workspace/shipping_ready/tgpl_oop/config/config_MLP_run/logs,
    maxSequenceLengthVector : [5000],
    batchSize : !!python/int 64,
    vectorizationTypeVector : ["binary"],
    epochsVector: [1,2],
    validationSplit : !!python/float 0.2,
    folderToSaveModels : !!python/str /home/knutf/workspace/model_folder,
    lossModel : !!python/str categorical_crossentropy,
    minNumArticlesPerDeweyVector : [50],
    kPreds : !!python/int 5,
    evaluatorConfigPath : !!python/str /home/knutf/workspace/shipping_ready/tgpl_oop/config/evaluator.yml
}