batchSize: 64
epochs: 3
evaluatorConfigPath: /home/knutf/workspace/shipping_ready/tgpl_oop/config/evaluator.yml
folderToSaveModels: /home/ubuntu/PycharmProjects_saved/tgpl_w_oop/testing/mlp
kPreds: 5
lossModel: categorical_crossentropy
maxSequenceLength: 5000
minNumArticlesPerDewey: 50
modelDir: null
trainingSetPath: /home/knutf/Dokumenter/test_fredag_mlp/test_fredag_mlp_training
validationSplit: 0.2
vectorizationType: binary
vocabSize: 2000
